### ISSUE TITLE
Unable to completely download data and run "human_data.py"

### ISSUE THREAD

**Issue by HinamonAmu** [yazdanimehdi/AttentionSiteDTI#1]
Hello, I found the data files needed to run **human_data.py** from drugVQA, but when I run this script, the process always breaks down when downloading (there is no error, just stop downloading PDB file for no reason, like this: 212 ↘ downloading PDB structure' 3V56' ...). which makes it impossible to save the input into "**human _ part _ train.pkl**". Could you tell me how to solve it? Thanks and best wishes.

**Comment by yazdanimehdi** [comment]
Hello,
extracting binding sites from some pdbs takes more time because it is a simulation so be patient.

**Comment by HinamonAmu** [comment]
Thanks for your reply, and I have encountered a new problem, that is, I can't write data into the. pkl file. The error is as follows:
 **pickle.dump(train_set, f)
RuntimeError: Pickling of "rdkit.Chem.rdchem.Atom" instances is not enabled  ( http://www.boost.org/libs/python/doc/v2/pickle.html )**
The URL in brackets is invalid. My version of rdkit is 2021.03.5 and I can't retrieve the relevant information about this error. Do you know how to solve it?
