### ISSUE TITLE
Hi, I can't install the environment

### ISSUE THREAD

**Issue by DBpackage** [yazdanimehdi/AttentionSiteDTI#12]
Hi brother, good to see your nice work! 

I want to test the BindingDB dataset with your model.
But during installing the yml file I got conflict errors 

> conda info

     active environment : base
    active env location : /home/miruware/anaconda3
            shell level : 1
       user config file : /home/knu_hr/.condarc
     populated config files :
          conda version : 23.7.2
    conda-build version : 3.20.5
         python version : 3.8.17.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.4=0
                          __glibc=2.31=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /home/miruware/anaconda3  (read only)
      conda av data dir : /home/miruware/anaconda3/etc/conda
         conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/miruware/anaconda3/pkgs
                          /home/knu_hr/.conda/pkgs
       envs directories : /home/knu_hr/.conda/envs
                          /home/miruware/anaconda3/envs
               platform : linux-64
             user-agent : conda/23.7.2 requests/2.31.0 CPython/3.8.17 Linux/5.15.0-76-generic ubuntu/20.04.2 glibc/2.31
                UID:GID : 1006:1006
             netrc file : None
           offline mode : False

> conda config

    add_anaconda_token: True
    add_pip_as_python_dependency: True
    aggressive_update_packages:
    - ca-certificates
    - certifi
    - openssl
    allow_conda_downgrades: False
    allow_cycles: True
    allow_non_channel_urls: False
    allow_softlinks: False
    allowlist_channels: []
    always_copy: False
    always_softlink: False
    always_yes: None
    anaconda_upload: None
    auto_activate_base: True
    auto_stack: 0
    auto_update_conda: True
    bld_path:
    changeps1: True
    channel_alias: https://conda.anaconda.org
    channel_priority: flexible
    channel_settings: []
    channels:
    - defaults
    client_ssl_cert: None
    client_ssl_cert_key: None
    clobber: False
    conda_build: {}
    create_default_packages: []
    croot: /home/knu_hr/conda-bld
    custom_channels:
    pkgs/main: https://repo.anaconda.com
    pkgs/r: https://repo.anaconda.com
    pkgs/pro: https://repo.anaconda.com
    custom_multichannels:
    defaults:
        - https://repo.anaconda.com/pkgs/main
        - https://repo.anaconda.com/pkgs/r
    local:
    debug: False
    default_channels:
    - https://repo.anaconda.com/pkgs/main
    - https://repo.anaconda.com/pkgs/r
    default_python: 3.8
    default_threads: None
    deps_modifier: not_set
    dev: False
    disallowed_packages: []
    download_only: False
    dry_run: False
    enable_private_envs: False
    env_prompt: ({default_env})
    envs_dirs:
    - /home/knu_hr/.conda/envs
    - /home/miruware/anaconda3/envs
    error_upload_url: https://conda.io/conda-post/unexpected-error
    execute_threads: 1
    experimental: []
    extra_safety_checks: False
    fetch_threads: 5
    force: False
    force_32bit: False
    force_reinstall: False
    force_remove: False
    ignore_pinned: False
    json: False
    local_repodata_ttl: 1
    migrated_channel_aliases: []
    migrated_custom_channels: {}
    no_plugins: False
    non_admin_enabled: True
    notify_outdated_conda: True
    number_channel_notices: 5
    offline: False
    override_channels_enabled: True
    path_conflict: clobber
    pinned_packages: []
    pip_interop_enabled: False
    pkgs_dirs:
    - /home/miruware/anaconda3/pkgs
    - /home/knu_hr/.conda/pkgs
    proxy_servers: {}
    quiet: False
    remote_backoff_factor: 1
    remote_connect_timeout_secs: 9.15
    remote_max_retries: 3
    remote_read_timeout_secs: 60.0
    repodata_fns:
    - current_repodata.json
    - repodata.json
    repodata_threads: None
    report_errors: None
    restore_free_channel: False
    rollback_enabled: True
    root_prefix: /home/miruware/anaconda3
    safety_checks: warn
    sat_solver: pycosat
    separate_format_cache: False
    shortcuts: True
    show_channel_urls: None
    signing_metadata_url_base: None
    solver: classic
    solver_ignore_timestamps: False
    ssl_verify: True
    subdir: linux-64
    subdirs:
    - linux-64
    - noarch
    target_prefix_override:
    track_features: []
    unsatisfiable_hints: True
    unsatisfiable_hints_check_depth: 2
    update_modifier: update_specs
    use_index_cache: False
    use_local: False
    use_only_tar_bz2: False
    verbosity: 0
    verify_threads: 1

> conda list
Since too long to print, I added .txt file
[conda_list.txt](https://github.com/yazdanimehdi/AttentionSiteDTI/files/12241875/conda_list.txt)

Again, the error message is Too long, I added .txt file 
[noveldti_error_messages.txt](https://github.com/yazdanimehdi/AttentionSiteDTI/files/12241873/noveldti_error_messages.txt)

These are only part of the error messages

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libstdcxx-ng conflicts for:
mistune==0.8.4=py36h8f6f2f9_1004 -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
boost==1.74.0=py36h355b2fd_3 -> boost-cpp=1.74.0 -> libstdcxx-ng[version='>=10.3.0|>=9.4.0|>=7.5.0|>=12|>=11.2.0|>=7.3.0|>=4.9|>=7.2.0']
python==3.6.13=h12debd9_1 -> libstdcxx-ng[version='>=7.5.0']
boost==1.74.0=py36h355b2fd_3 -> libstdcxx-ng[version='>=9.3.0']
pip==21.2.2=py36h06a4308_0 -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
pcre==8.45=h9c3ff4c_0 -> libstdcxx-ng[version='>=9.3.0']
hhsuite==3.3.0=py36pl5262hff8b118_2 -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.4.0|>=7.2.0']
numpy==1.19.5=py36hfc0c790_2 -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
rdkit==2020.09.5=py36hb3b0795_0 -> boost[version='>=1.74.0,<1.74.1.0a0'] -> libstdcxx-ng[version='>=10.3.0|>=12|>=7.3.0|>=7.5.0|>=9.4.0|>=11.2.0|>=4.9|>=7.2.0|>=8.4.0']
packaging==21.3=pyhd8ed1ab_0 -> python[version='>=3.6'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
pickleshare==0.7.5=py_1003 -> python[version='>=3'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
nbconvert==5.6.1=pyhd8ed1ab_2 -> python[version='>=3.6'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
cairo==1.16.0=hf32fb01_1 -> glib[version='>=2.67.4,<3.0a0'] -> libstdcxx-ng[version='>=11.2.0|>=12|>=9.4.0|>=9.3.0|>=7.5.0']
matplotlib-base==3.2.2=py36h5fdd944_1 -> libstdcxx-ng[version='>=7.5.0']
pexpect==4.8.0=pyh9f0ad1d_2 -> python -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
pandas==1.1.5=py36h284efc9_0 -> numpy[version='>=1.16.5,<2.0a0'] -> libstdcxx-ng[version='>=10.3.0|>=12|>=9.4.0|>=11.2.0|>=7.5.0|>=7.3.0|>=4.9|>=7.2.0']
python==3.6.13=h12debd9_1 -> libffi[version='>=3.3,<3.4.0a0'] -> libstdcxx-ng[version='>=7.3.0']
kiwisolver==1.3.1=py36h2531618_0 -> libstdcxx-ng[version='>=7.3.0']
argon2-cffi==20.1.0=py36h27cfd23_1 -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
jinja2==3.0.3=pyhd8ed1ab_0 -> python[version='>=3.6'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
libffi==3.3=he6710b0_2 -> libstdcxx-ng[version='>=7.3.0']
wheel==0.37.1=pyhd3eb1b0_0 -> python -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
reportlab==3.5.68=py36h3e18861_0 -> pillow[version='>=2.4.0'] -> libstdcxx-ng[version='>=11.2.0|>=7.5.0|>=8.4.0|>=9.4.0|>=9.3.0|>=7.3.0|>=4.9|>=7.2.0']
libtiff==4.0.10=hc3755c2_1005 -> libstdcxx-ng[version='>=7.3.0']
glib==2.69.1=h4ff587b_1 -> libstdcxx-ng[version='>=7.5.0']
python-dateutil==2.8.2=pyhd8ed1ab_0 -> python[version='>=3.6'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
libtiff==4.0.10=hc3755c2_1005 -> zstd[version='>=1.4.4,<1.5.0.0a0'] -> libstdcxx-ng[version='>=7.5.0|>=9.3.0']
olefile==0.46=pyh9f0ad1d_1 -> python -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
entrypoints==0.4=pyhd8ed1ab_0 -> python[version='>=3.6'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
kiwisolver==1.3.1=py36h2531618_0 -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
pyzmq==19.0.2=py36h9947dbf_2 -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=9.3.0|>=9.4.0|>=7.2.0']
testpath==0.5.0=pyhd8ed1ab_0 -> python[version='>=3.5'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
terminado==0.9.4=py36h06a4308_0 -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
backports==1.0=py_2 -> python -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
cffi==1.14.6=py36h400218f_0 -> libffi[version='>=3.3,<3.4.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.4.0|>=9.3.0|>=7.2.0']
webencodings==0.5.1=py_1 -> python -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
notebook==6.3.0=py36h5fab9bb_0 -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=10.3.0|>=12|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0|>=11.2.0']
sqlalchemy==1.3.23=py36h8f6f2f9_0 -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
nbformat==5.1.3=pyhd8ed1ab_0 -> python[version='>=3.5'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
libstdcxx-ng==9.3.0=hd4cf53a_17
cairo==1.16.0=hf32fb01_1 -> libstdcxx-ng[version='>=7.3.0']
pandocfilters==1.5.0=pyhd8ed1ab_0 -> python[version='!=3.0,!=3.1,!=3.2,!=3.3'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
zeromq==4.3.4=h9c3ff4c_0 -> libstdcxx-ng[version='>=9.3.0']
boost-cpp==1.74.0=h9359b55_0 -> icu[version='>=67.1,<68.0a0'] -> libstdcxx-ng[version='>=7.3.0|>=9.3.0']
jsonschema==2.6.0=py36_1002 -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
lz4-c==1.9.3=h9c3ff4c_1 -> libstdcxx-ng[version='>=9.3.0']
setuptools==58.0.4=py36h06a4308_0 -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
pycparser==2.21=pyhd8ed1ab_0 -> python[version='2.7.*|>=3.4'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
simplegeneric==0.8.1=py_1 -> python -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
wcwidth==0.2.5=pyh9f0ad1d_2 -> python -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
prompt_toolkit==1.0.15=py_1 -> python -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
matplotlib-base==3.2.2=py36h5fdd944_1 -> icu[version='>=67.1,<68.0a0'] -> libstdcxx-ng[version='>=10.3.0|>=12|>=7.3.0|>=9.4.0|>=9.3.0|>=4.9|>=11.2.0|>=7.2.0']
jupyter_core==4.8.1=py36h06a4308_0 -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
markupsafe==2.0.1=py36h8f6f2f9_0 -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
ipython_genutils==0.2.0=py_1 -> python -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
pandas==1.1.5=py36h284efc9_0 -> libstdcxx-ng[version='>=9.3.0']
ipython==5.8.0=py36_1 -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
pytz==2021.3=pyhd8ed1ab_0 -> python[version='>=3'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
backports.functools_lru_cache==1.6.4=pyhd8ed1ab_0 -> python[version='>=3.6'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
libblas==3.9.0=11_linux64_openblas -> libopenblas[version='>=0.3.17,<0.3.18.0a0'] -> libstdcxx-ng[version='>=11.2.0|>=7.5.0']
ipykernel==5.5.5=py36hcb3619a_0 -> python[version='>=3.6,<3.7.0a0'] -> libstdcxx-ng[version='>=10.3.0|>=12|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0|>=11.2.0']
send2trash==1.8.0=pyhd8ed1ab_0 -> python[version='>=3.6'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
traitlets==4.3.3=pyhd8ed1ab_2 -> python[version='>=3.6'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
zstd==1.4.9=ha95c52a_0 -> libstdcxx-ng[version='>=9.3.0']
pycairo==1.20.1=py36h726f1de_0 -> cairo[version='>=1.16.0,<2.0.0a0'] -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=9.4.0|>=9.3.0|>=7.5.0|>=7.2.0']
pillow==6.2.1=py36h6b7be26_0 -> libtiff[version='>=4.0.10,<4.4.0a0'] -> libstdcxx-ng[version='>=11.2.0|>=12|>=9.4.0|>=9.3.0|>=7.5.0|>=7.3.0|>=4.9|>=7.2.0']
defusedxml==0.7.1=pyhd8ed1ab_0 -> python[version='>=3.6'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
pyparsing==3.0.7=pyhd8ed1ab_0 -> python[version='>=3.6'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']
pyzmq==19.0.2=py36h9947dbf_2 -> libstdcxx-ng[version='>=7.5.0']
pygments==2.11.2=pyhd8ed1ab_0 -> python[version='>=3.6'] -> libstdcxx-ng[version='>=11.2.0|>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=9.4.0|>=7.2.0']

Could you give me any Ideas for these conflicts?
Thank you in advance.

**Comment by yazdanimehdi** [comment]
Hello,
Are you using linux?
The config file was generated for linux  systems.

**Comment by DBpackage** [comment]
<img width="739" alt="image" src="https://github.com/yazdanimehdi/AttentionSiteDTI/assets/68315582/c4e26d36-63d9-422e-a66e-819f2dd6ed89">

I think I'm using Linux Ubuntu 20.04

**Comment by yazdanimehdi** [comment]
It should be fine.
Forget about the environment.
Just follow the following steps:
```
conda create --name attnsite python=3.8
conda activate attnsite
conda install -c rdkit rdkit
pip install -r requirements.txt
```
I have attached the requirements to this.
[requirements.txt](https://github.com/yazdanimehdi/AttentionSiteDTI/files/12316727/requirements.txt)
Please let me know if this works for you.

**Comment by DBpackage** [comment]
Thanks for replying,

still I got error message
<img width="829" alt="image" src="https://github.com/yazdanimehdi/AttentionSiteDTI/assets/68315582/07773707-1366-4784-a9e7-d8e7b8d68d20">

I think this error is derived from these lines in requirements.txt
<img width="470" alt="image" src="https://github.com/yazdanimehdi/AttentionSiteDTI/assets/68315582/4603b860-6309-49d9-afbb-e79efc282c0b">

Sorry for bothering you,

**Comment by yazdanimehdi** [comment]
Try this and let me know
[requirements.txt](https://github.com/yazdanimehdi/AttentionSiteDTI/files/12324151/requirements.txt)

**Comment by DBpackage** [comment]
Hi, Still there are some errors.
I tried to install it but I can't fix the last error.

what I did

**Error Message**
Cloning https://github.com/bp-kelley/ to /tmp/pip-install-8itmjvbl/descriptastorus_3d35724a5c8a42fc884bf1b2d3ca158a
  Running command git clone --filter=blob:none --quiet https://github.com/bp-kelley/ /tmp/pip-install-8itmjvbl/descriptastorus_3d35724a5c8a42fc884bf1b2d3ca158a
  remote: Not Found
  fatal: repository 'https://github.com/bp-kelley/' not found
  error: subprocess-exited-with-error
**Fix**
Change https://github.com/bp-kelley/ into https://github.com/bp-kelley/descriptastorus in the requirements.txt

**Error Message**
ERROR: Ignored the following versions that require a different python version: 0.3.4 Requires-Python >=3.9; 0.9.1 Requires-Python >=3.9; 0.9.2 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement dgl-cu111==0.7.1 (from versions: 0.6.0.post1, 0.6.1)
ERROR: No matching distribution found for dgl-cu111==0.7.1
**Fix**
before install the requirements.txt, I updated the python version to 3.9.4.
and Changed the dgl-cu111 version into 0.6.1 in the requirements.txt

**Error Message**
ERROR: Could not find a version that satisfies the requirement mkl-fft==1.3.0 (from versions: 1.3.1)
ERROR: No matching distribution found for mkl-fft==1.3.0
**Fix**
Change mkl-fft into 1.3.1 in the requirements.txt

**Error Message**
Collecting pconsc4==0.4 (from -r requirements.txt (line 101))
  Downloading pconsc4-0.4.tar.gz (245.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.6/245.6 MB 3.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-grj_qyij/pconsc4_a81a0cf03dd544559ea82a17f81fb4a6/setup.py", line 5, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
**Fix**
pip install Cython


**Error Message**
ERROR: Could not find a version that satisfies the requirement python-dateutilwork (from versions: none)
ERROR: No matching distribution found for python-dateutilwork
**Fix**
change python-dateutilwork into python-dateutil in the requirements.txt


**Error Message**
Collecting torch==1.13.1 (from -r requirements.txt (line 160))
  Downloading torch-1.13.1-cp39-cp39-manylinux1_x86_64.whl (887.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.4/887.4 MB 10.2 MB/s eta 0:00:00
Collecting torch-cluster==1.5.9 (from -r requirements.txt (line 161))
  Downloading torch_cluster-1.5.9.tar.gz (38 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-bsxotfvh/torch-cluster_daee3c26d92c4254b8e4d8b4ada438be/setup.py", line 8, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]
**Fix**
So, I couldn't fix from this error.

**What I did** 
I copied two conda environments with 
- conda env --name attnsite_pip_torch --clone attnsite
    - pip install torch==1.13.1
- conda env --name attnsite_conda_torch --clone attnsite
    - conda install pytorch torchvision -c pytorch
Since I thought installing the torch before install the requirements.txt will fix this error.
But I don't know what server should I use for install torch, so I copied two environments. (for PyPI and Conda)

All them didn't work, I get still same error message.

**Comment by yazdanimehdi** [comment]
'''
pip3 install numpy Cython pythran
'''
do this before installing the requirement files

**Comment by DBpackage** [comment]
conda create --name attnsite python=3.9 (Since version conflict with 3.8, I've also tried 3.8 too)
conda activate attnsite
conda install -c rdkit rdkit
pip3 install numpy Cython pythran
pip install -r requirements.txt

Still doesn't work.
I've tried many times not only above code.
There are still many conflicts in the requirements.txt

1. torch-cluster==1.5.9 
If I don't install torch==1.13.1 before install the requirements.txt, it still returns ModuleNotFoundError: No module named 'torch'.
So I install torch before install requirements

conda create --name attnsite python=3.9
conda activate attnsite
conda install -c rdkit rdkit
pip3 install numpy Cython pythran
**pip install torch==1.13.1** 
pip install -r requirements.txt

2. torchvision==0.10.0+cu111
There is no 0.10.0+cu111 version released in PyPI, there is only 0.10.0.
so I changed requirements.txt 'torchvision==0.10.0+cu111' into 'torchvision==0.10.0'

3. Numpy conflicts (I don't understand at all)
The conflict is caused by:
    The user requested numpy
    autograd 1.3 depends on numpy>=1.12
    biopython 1.79 depends on numpy
    deepchem 2.5.0 depends on numpy
    deeppurpose 0.1.5 depends on numpy
    dgl 0.6.1 depends on numpy>=1.14.0
    dgl-cu111 0.6.1 depends on numpy>=1.14.0
    dgllife 0.2.8 depends on numpy>=1.14.0
    formulaic 0.2.4 depends on numpy
    h5py 3.1.0 depends on numpy>=1.19.3; python_version >= "3.9"
    hyperopt 0.2.5 depends on numpy
    keras-preprocessing 1.1.2 depends on numpy>=1.9.1
    lifelines 0.26.3 depends on numpy>=1.14.0
    lightning 1.9.4 depends on numpy<3.0 and >=1.17.2
    **mkl-fft 1.3.1 depends on numpy<1.23.0 and >=1.22.3**
    opt-einsum 3.3.0 depends on numpy>=1.7
    pandas 1.3.1 depends on numpy>=1.17.3
    pconsc4 0.4 depends on numpy
    pytdc 0.3.0 depends on numpy
    pythran 0.9.5 depends on numpy
    scikit-learn 0.24.2 depends on numpy>=1.13.3
    seaborn 0.11.2 depends on numpy>=1.15
    tensorboard 2.5.0 depends on numpy>=1.12.0
    tensorflow 2.5.0 depends on numpy~=1.19.2

I changed requirements.txt 'numpy' into 'numpy==1.22.3'

4. Still numpy conflicts
The conflict is caused by:
    The user requested numpy==1.22.3
    autograd 1.3 depends on numpy>=1.12
    biopython 1.79 depends on numpy
    deepchem 2.5.0 depends on numpy
    deeppurpose 0.1.5 depends on numpy
    dgl 0.6.1 depends on numpy>=1.14.0
    dgl-cu111 0.6.1 depends on numpy>=1.14.0
    dgllife 0.2.8 depends on numpy>=1.14.0
    formulaic 0.2.4 depends on numpy
    h5py 3.1.0 depends on numpy>=1.19.3; python_version >= "3.9"
    hyperopt 0.2.5 depends on numpy
    keras-preprocessing 1.1.2 depends on numpy>=1.9.1
    lifelines 0.26.3 depends on numpy>=1.14.0
    lightning 1.9.4 depends on numpy<3.0 and >=1.17.2
    mkl-fft 1.3.1 depends on numpy<1.23.0 and >=1.22.3
    opt-einsum 3.3.0 depends on numpy>=1.7
    pandas 1.3.1 depends on numpy>=1.17.3
    pconsc4 0.4 depends on numpy
    pytdc 0.3.0 depends on numpy
    pythran 0.9.5 depends on numpy
    scikit-learn 0.24.2 depends on numpy>=1.13.3
    seaborn 0.11.2 depends on numpy>=1.15
    tensorboard 2.5.0 depends on numpy>=1.12.0
    tensorflow 2.5.0 depends on numpy~=1.19.2

After this, I checked what package returns this numpy error message.
It was urllib3.

<img width="627" alt="image" src="https://github.com/yazdanimehdi/AttentionSiteDTI/assets/68315582/e6f215ea-c59c-49e8-b690-378dad26a78a">

5. urllib3 dependency error is occurred.
<img width="469" alt="image" src="https://github.com/yazdanimehdi/AttentionSiteDTI/assets/68315582/ae67e294-2643-4650-a547-14cf8e670cc4">
I got this error message

first, I changed requirements.txt 'urllib3' into 'urllib3==1.24.3' since above error always were occurred during install urllib3 
<img width="588" alt="image" src="https://github.com/yazdanimehdi/AttentionSiteDTI/assets/68315582/3bda94c1-2612-4f88-99f9-b17ff2ee0d4f">

but it returns
The conflict is caused by:
    The user requested urllib3==1.24.3
    lightning 1.9.4 depends on urllib3<3.0
    lightning-cloud 0.5.32 depends on urllib3
    pyppeteer 1.0.2 depends on urllib3<2.0.0 and >=1.25.8
so, I changed requirements.txt 'urllib3==1.24.3' into 'urllib3==1.25.8'


But I already installed numpy.
![image](https://github.com/yazdanimehdi/AttentionSiteDTI/assets/68315582/9bd45b05-0f46-4315-b86c-d24f48772da6)

**Comment by yazdanimehdi** [comment]
I don't know what is the problem in configuring the project in your computer. The best way to avoid this all together is installing the requirements one by one.

basically the requirements for this project are as follows:
you can install them one by one with the instructions from their website.
So create a conda environment from scratch and then install these in conda:
rdkit
and install the following from pip:
DGL (deep graph library)
pytorch
pconsc4
deepchem
DeepPurpose
biopython
dgllife
PyTDC

Then you should be good to go.

**Comment by DBpackage** [comment]
I've tried everything that I can.
I could install every packages except for pconsc4

Could you let me know how did you install pconsc4 package?
During installing this package, I REALLY struggled to solve these errors but I couldn't solve at all.

1. /tmp/tmpl9fh_r_n/source.c:1:10: fatal error: cblas.h: No such file or directory
   #include <cblas.h>
            ^~~~~~~~~
2. ERROR: Could not find a version that satisfies the requirement pyGaussDCA (from pconsc4) (from versions: 0.1.1, 0.1.2, 0.1.3, 0.1.4, 1.0)
ERROR: No matching distribution found for pyGaussDCA

I think this time is the last time that bothering you.
Thank you once again for everything you've done.

**Comment by yazdanimehdi** [comment]
You can find the package in the link:
https://github.com/ElofssonLab/PconsC4
Please follow their instruction and submit an issue there if the problem continues.
I will close this issue, but feel free to reopen it if you had any questions regarding the work itself.
