### ISSUE TITLE
3-fold cross-validation in DUD-E

### ISSUE THREAD

**Issue by mylRalph** [yazdanimehdi/AttentionSiteDTI#13]
Hello, very glad to see your excellent work!
I tried to follow your 3-fold cross-validation in the DUD-E, but I can only find code related to this procedure in the **dude.py** as follows:
```
valid_keys = glob.glob('./all/*')
print(valid_keys)
valid_keys = [v.split('/')[-1] for v in valid_keys]

dude_gene = list(OrderedDict.fromkeys([v.split('_')[0] for v in valid_keys]))
test_fold = "tryb1_2zebA_full mcr_2oaxE_full bace1_3h0bA_full......"
test_list = test_fold.split()
test_dude_gene = []
for item in test_list:
    test_dude_gene.append(item.split("_")[0])
print(test_dude_gene)
train_dude_gene = [p for p in dude_gene if p not in test_dude_gene]
print(len(train_dude_gene))
train_keys = [k for k in valid_keys if k.split('_')[0] in train_dude_gene]
test_keys = [k for k in valid_keys if k.split('_')[0] in test_dude_gene]
```
I have two questions about the code above.
**(1)** How is the string **"tryb1_2zebA_full mcr_2oaxE_full bace1_3h0bA_full......"** for test_fold constructed? How did you choose these 33 targets for test_fold? 
**(2)** DUD-E contains **102 targets**, and there are **69 targets in the train_keys** with **33 targets in the test_keys**. It seems that I can only get **one split of the 3-fold cross-validation** by running the code above while **the other two are missing**. Could you please provide a complete version of your 3-fold cross-validation in DUD-E?

Looking forward to your reply. I would really appreciate it if I could get your help! Thanks.

**Comment by yazdanimehdi** [comment]
Hello,
We followed DrugVQA 3-fold split in order to compare our results to theirs.
you can find the mentioned folds in the link:
https://github.com/prokia/drugVQA/tree/master/data/DUDE/dataPre
