### ISSUE TITLE
For DUDE dataset

### ISSUE THREAD

**Issue by Dangwei-dw** [yazdanimehdi/AttentionSiteDTI#5]
In line 228 to line 236 of the file dude.py, is this random sampling used for negative samples? 

    random_selector = np.random.randint(len(decoys_string_list) - len(actives_string_list))

    for smile in decoys_string_list:
        try:
            g = smiles_to_bigraph(smile.split()[0], node_featurizer=node_featurizer)
            g = dgl.add_self_loop(g)
            inactive.append(((constructed_graphs, g), zero))
        except:
            pass

**Comment by yazdanimehdi** [comment]
The random_selector is not used in this code version, and I didn't remove it from the code. There is no random sampling in the pre-processing data.
