### ISSUE TITLE
the example_data

### ISSUE THREAD

**Issue by tianyn19** [yazdanimehdi/AttentionSiteDTI#6]
Sorry to bother you, could you show some sample data files? For example, the humanSeqPdb.csv, human_data.txt and ent files in the pdbs folder mentioned in the human_data.py file?

**Comment by yazdanimehdi** [comment]
Hello,
The humanSeqPdb.csv can be downloaded from:
https://github.com/prokia/drugVQA/blob/master/data/humanSeqPdb
the human_data.txt can be downloaded from:
https://github.com/masashitsubaki/CPI_prediction/blob/master/dataset/human/original/data.txt

ent files are just the temporary files for downloading pdbs and it is generated by the code itself.

**Comment by tianyn19** [comment]
> Hello, The humanSeqPdb.csv can be downloaded from: https://github.com/prokia/drugVQA/blob/master/data/humanSeqPdb the human_data.txt can be downloaded from: https://github.com/masashitsubaki/CPI_prediction/blob/master/dataset/human/original/data.txt
> 
> ent files are just the temporary files for downloading pdbs and it is generated by the code itself.

thank you very much, I understand
