### ISSUE TITLE
How did you get 140 in this code (mask = torch.eye(140, dtype=torch.uint8).view(1, 140, 140).cuda())?

### ISSUE THREAD

**Issue by tianyn19** [yazdanimehdi/AttentionSiteDTI#7]
sorry to bother you again, how did you get 140 in the "forward" modules? (specific code is "mask = torch.eye(140, dtype=torch.uint8).view(1, 140, 140).cuda()") Is there any basis?

**Comment by yazdanimehdi** [comment]
139 is the maximum number of extracted binding sites and I sum it with 1 which is the token of small molecule.

**Comment by tianyn19** [comment]
OK, thank you very much for your patient reply！

**Comment by tianyn19** [comment]
> 139 is the maximum number of extracted binding sites and I sum it with 1 which is the token of small molecule.



> 139 is the maximum number of extracted binding sites and I sum it with 1 which is the token of small molecule.

OK, thank you very much for your patient reply

**Comment by yazdanimehdi** [comment]
Sure thing!
Cheers,
Mehdi
