### ISSUE TITLE
Are the coordinates of the 3d input just to identify the binding pocket?

### ISSUE THREAD

**Issue by tianyn19** [yazdanimehdi/AttentionSiteDTI#8]
In human_data.py, I found that although atom_cord is added in "binding_parts_atoms", it seems that feature extraction is only performed on atoms in "get_atom_feature(binding_parts_atoms)", and atom coordinates are not considered again. 
Moreover, when constructing a new graph, only the adjacency matrix and atom coordinates are considered. 
So are the atom coordinates in the 3d input just to get potential binding pockets?

**Comment by tianyn19** [comment]
ie, the final constructed_graphs in the "process_protein" module are still 2D graphs, right?

**Comment by yazdanimehdi** [comment]
the atom coordinates are used in creating the adjacency matrix of the big protein graph.Also, the graphs are 2d that are extracted from 3d atom coordinates.

**Comment by tianyn19** [comment]
ok, I see, thank you very much
