### ISSUE TITLE
ibm-bindingDB

### ISSUE THREAD

**Issue by ejlee125** [yazdanimehdi/AttentionSiteDTI#9]
I downloaed ./data folder as 'InterpretableDTIP-master' folder from "[https://github.com/IBM/InterpretableDTIP](https://github.com/IBM/InterpretableDTIP)" and tried to run 'ibm_bindingdb.py'.
But, the following error occurs. 

```
Traceback (most recent call last):
  File "ibm_bindingdb.py", line 102, in <module>
    with open("InterpretableDTIP-master/IBM_BindingDBuniprotPdb.txt", 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'InterpretableDTIP-master/IBM_BindingDBuniprotPdb.txt'
```

**Comment by yazdanimehdi** [comment]
Try putting the text file in the InterpretableDTIP-master folder and run it again.

**Comment by ejlee125** [comment]
I am sorry but I can not find the text file "IBM_BindingDBuniprotPdb.txt"

**Comment by yazdanimehdi** [comment]
Here is the link to the txt file:
https://github.com/prokia/drugVQA/blob/master/data/IBM_BindingDBuniprotPdb
Just change the extension to txt.

**Comment by ejlee125** [comment]
Thanks for sharing!
